
# Code overview for tutor

This notebook gives a high-level explanation of the implementation supporting the thesis. It is designed so that a reviewer can understand **what the code does** without reading all MATLAB files line by line.

The key point is that the thesis tables are **not hardcoded**. The MATLAB scripts build or load BFM models, apply scenario evidence, run BFM inference, parse the resulting belief functions, and export structured CSV files. The thesis tables are then generated from those CSVs.


## 1. File types in this repository

| File type | Role |
|---|---|
| `.m` MATLAB scripts | Run BFM experiments and export CSV results. |
| `.txt` UIL files | Human-readable source models for BFM: variables, relations, valuations, priors, and ignorance. |
| `.mat` files | Generated MATLAB/BFM model objects. Useful for rerunning, not ideal for explanation. |
| `.csv` files | Final structured result tables: belief, plausibility, width, conflict, rankings. |
| diary `.txt` files | MATLAB run logs proving the workflow was executed. |

In [1]:

from pathlib import Path
import pandas as pd

ROOT = Path('..').resolve()
print(ROOT)

paths = {
    'matlab_scripts': ROOT / 'matlab' / 'export_scripts',
    'uil': ROOT / 'bfm_models' / 'uil',
    'results': ROOT / 'results' / 'raw',
    'diaries': ROOT / 'results' / 'diaries'
}

for name, path in paths.items():
    print(f"{name:15s}: {path}")

/mnt/data/belief-network-fault-diagnosis-final
matlab_scripts : /mnt/data/belief-network-fault-diagnosis-final/matlab/export_scripts
uil            : /mnt/data/belief-network-fault-diagnosis-final/bfm_models/uil
results        : /mnt/data/belief-network-fault-diagnosis-final/results/raw
diaries        : /mnt/data/belief-network-fault-diagnosis-final/results/diaries


## 2. Overall workflow

The implementation follows the same pattern across the experiment levels:

```text
Base UIL model / generated UIL variant
      ↓
uil2bm converts UIL into a BFM .mat model
      ↓
condiembed transforms conditional beliefs into ordinary embedded beliefs
      ↓
scenario evidence is created as belief functions
      ↓
solve is called for every fault variable
      ↓
showbel output is parsed into belief / plausibility / width / conflict
      ↓
writetable exports a CSV used in the thesis tables
```

Only the **scenario definitions**, the **incompleteness rules**, and the **fault-variable mapping** are explicitly specified. The diagnostic results themselves are produced by BFM inference.

In [2]:

# Show where the main BFM workflow calls appear in each MATLAB script.
keywords = ['uil2bm', 'condiembed', 'keepbel', 'solve(', 'showbel', 'writetable']
for script in sorted(paths['matlab_scripts'].glob('export_bfm_*.m')):
    print('\n' + '='*90)
    print(script.name)
    text = script.read_text(errors='ignore').splitlines()
    for i, line in enumerate(text, start=1):
        if any(k in line for k in keywords):
            print(f"{i:4d}: {line.strip()}")

==========================================================================================
export_bfm_L0_results.m
  41: embelall = condiembed([BELIEF(:).number]);
  44: keepbel(embelall);
  98: showbel(obs);
 113: result = solve(beliefs_with_evidence, bfm_var);
 158: writetable(T, out_path);
 239: % showbel returns a character array representation of the mass table.
 240: tbl = showbel(result_belief_id);

==========================================================================================
export_bfm_L1_local_prior_ignorance.m
 152: uil2bm(temp_uil, temp_bm_file);
 158: embelall = condiembed([BELIEF(:).number]);
 161: keepbel(embelall);
 172: showbel(obs);
 191: result = solve(beliefs_with_evidence, bfm_var);
 236: writetable(T, out_path);
 361: tbl = showbel(result_belief_id);

==========================================================================================
export_bfm_L2_fault_family_prior_ignorance.m
 167: uil2bm(temp_uil, temp_bm_file);
 173: embelall = condiembed([BELIEF(:).number]);
 176: keepbel(embelall);
 187: showbel(obs);
 206: result = solve(beliefs_with_evidence, bfm_var);
 268: writetable(T, out_path);
 445: tbl = showbel(result_belief_id);

==========================================================================================
export_bfm_L3_observation_uncertainty.m
  54: embelall = condiembed([BELIEF(:).number]);
  57: keepbel(embelall);
 116: showbel(obs);
 135: result = solve(beliefs_with_evidence, bfm_var);
 197: writetable(T, out_path);
 330: tbl = showbel(result_belief_id);

==========================================================================================
export_bfm_L3b_observation_rule_uncertainty.m
 171: uil2bm(l3b_uil, bm_file);
 174: error(['uil2bm did not create ', bm_file, '.mat. Check UIL syntax above.']);
 181: embelall = condiembed([BELIEF(:).number]);
 184: keepbel(embelall);
 237: showbel(obs);
 252: result = solve(beliefs_with_evidence, bfm_var);
 307: writetable(T, out_path);
 396: tbl = showbel(result_belief_id);

==========================================================================================
export_bfm_L4_combined_incompleteness.m
 180: uil2bm(temp_uil, temp_bm_file);
 183: error(['uil2bm did not create ', temp_bm_file, '.mat. Check UIL syntax.']);
 190: embelall = condiembed([BELIEF(:).number]);
 193: keepbel(embelall);
 204: showbel(obs);
 223: result = solve(beliefs_with_evidence, bfm_var);
 285: writetable(T, out_path);
 544: tbl = showbel(result_belief_id);


## 3. UIL source models: what BFM reads

The UIL files are the most readable representation of the belief network. They define:

- fault variables such as `PSF`, `Batt`, `SW3`, `C3`, and `LF`;
- voltage variables `V0`--`V8`;
- observation variables such as LEDs and multimeter readings;
- priors or vacuous priors;
- deterministic physical relations, such as voltage propagation;
- visual observation rules and measurement rules.

For example, the L0 UIL file defines variables and relations directly. The temporary L1/L2/L4 UIL files are generated by MATLAB scripts from the base L0 model and show how incompleteness is represented.

In [3]:

# Inspect the first part of the L0 UIL model.
l0_uil = paths['uil'] / 'L0_complete' / 'ten_cube_L0_complete_s8.txt'
print(l0_uil)
print('\n'.join(l0_uil.read_text(errors='ignore').splitlines()[:45]))

/mnt/data/belief-network-fault-diagnosis-final/bfm_models/uil/L0_complete/ten_cube_L0_complete_s8.txt
# 10-cube fault diagnosis model - L0 complete - Scenario 8 reference model
# Generated by run_10cube_L0_scenario8.m
# Short BFM variable names are used to avoid display truncation.

DEFINE VARIABLE PSF {no yes};
DEFINE VARIABLE Batt {good exh};
DEFINE VARIABLE SW1 {ok det};
DEFINE VARIABLE SW2 {ok det};
DEFINE VARIABLE SW3 {ok det};
DEFINE VARIABLE SW4 {ok det};
DEFINE VARIABLE SW5 {ok det};
DEFINE VARIABLE SW6 {ok det};
DEFINE VARIABLE SW7 {ok det};
DEFINE VARIABLE SW8 {ok det};
DEFINE VARIABLE C1 {ok bro};
DEFINE VARIABLE C2 {ok bro};
DEFINE VARIABLE C3 {ok bro};
DEFINE VARIABLE C4 {ok bro};
DEFINE VARIABLE C5 {ok bro};
DEFINE VARIABLE C6 {ok bro};
DEFINE VARIABLE C7 {ok bro};
DEFINE VARIABLE C8 {ok bro};
DEFINE VARIABLE CL {ok bro};
DEFINE VARIABLE LF {ok bro};
DEFINE VARIABLE V0 {v12 v0};
DEFINE VARIABLE V1 {v12 v0};
DEFINE VARIABLE V2 {v12 v0};
DEFINE VARIABLE V3 {v12 v0};
DEFINE VARIABLE V4 {v12 v0};
DEFINE VARIABLE V5 {v12 v0};
DEFINE VARIABLE V6 {v12 v0};
DEFINE VARIABLE V7 {v12 v0};
DEFINE VARIABLE V8 {v12 v0};
DEFINE VARIABLE OPSU {on off};
DEFINE VARIABLE I1 {on off};
DEFINE VARIABLE I2 {on off};
DEFINE VARIABLE I3 {on off};
DEFINE VARIABLE I4 {on off};
DEFINE VARIABLE I5 {on off};
DEFINE VARIABLE I6 {on off};
DEFINE VARIABLE I7 {on off};
DEFINE VARIABLE I8 {on off};
DEFINE VARIABLE OLa {on off};
DEFINE VARIABLE OLi {on off};
DEFINE VARIABLE MB {v12 v0};

In [4]:

# Find representative UIL lines: priors, conditional priors, physical relations, and observation rules.
uil_text = l0_uil.read_text(errors='ignore').splitlines()
patterns = ['SET VALUATION PR_PSF', 'SET CONDITIONAL VALUATION PB0', 'DEFINE RELATION R_V3',
            'SET VALUATION R_V3', 'SET VALUATION R_I3', 'SET VALUATION R_M3']
for pattern in patterns:
    print('\n---', pattern, '---')
    for i, line in enumerate(uil_text, start=1):
        if pattern in line:
            for j in range(i, min(i+10, len(uil_text)+1)):
                print(f"{j:4d}: {uil_text[j-1]}")
            break

--- SET VALUATION PR_PSF ---
  78: SET VALUATION PR_PSF {yes} 0.005, {no} 0.995;
  79: SET CONDITIONAL VALUATION PB0 GIVEN {no}, {exh} 0.080, {good} 0.920;
  80: SET CONDITIONAL VALUATION PB1 GIVEN {yes}, {exh} 0.950, {good} 0.050;
  81: SET VALUATION PR_SW1 {det} 0.030, {ok} 0.970;
  82: SET VALUATION PR_SW2 {det} 0.030, {ok} 0.970;
  83: SET VALUATION PR_SW3 {det} 0.030, {ok} 0.970;
  84: SET VALUATION PR_SW4 {det} 0.030, {ok} 0.970;
  85: SET VALUATION PR_SW5 {det} 0.030, {ok} 0.970;
  86: SET VALUATION PR_SW6 {det} 0.030, {ok} 0.970;
  87: SET VALUATION PR_SW7 {det} 0.030, {ok} 0.970;

--- SET CONDITIONAL VALUATION PB0 ---
  79: SET CONDITIONAL VALUATION PB0 GIVEN {no}, {exh} 0.080, {good} 0.920;
  80: SET CONDITIONAL VALUATION PB1 GIVEN {yes}, {exh} 0.950, {good} 0.050;
  81: SET VALUATION PR_SW1 {det} 0.030, {ok} 0.970;
  82: SET VALUATION PR_SW2 {det} 0.030, {ok} 0.970;
  83: SET VALUATION PR_SW3 {det} 0.030, {ok} 0.970;
  84: SET VALUATION PR_SW4 {det} 0.030, {ok} 0.970;
  85: SET VALUATION PR_SW5 {det} 0.030, {ok} 0.970;
  86: SET VALUATION PR_SW6 {det} 0.030, {ok} 0.970;
  87: SET VALUATION PR_SW7 {det} 0.030, {ok} 0.970;
  88: SET VALUATION PR_SW8 {det} 0.030, {ok} 0.970;

--- DEFINE RELATION R_V3 ---
 103: DEFINE RELATION R_V3 {V2 C3 SW3 V3};
 104: DEFINE RELATION R_V4 {V3 C4 SW4 V4};
 105: DEFINE RELATION R_V5 {V4 C5 SW5 V5};
 106: DEFINE RELATION R_V6 {V5 C6 SW6 V6};
 107: DEFINE RELATION R_V7 {V6 C7 SW7 V7};
 108: DEFINE RELATION R_V8 {V7 C8 SW8 V8};
 109:
 110: SET VALUATION R_V0 {
 111: (no good v12)
 112: (no exh v0)

--- SET VALUATION R_V3 ---
 139: SET VALUATION R_V3 {
 140: (v12 ok ok v12)
 141: (v12 ok det v0)
 142: (v12 bro ok v0)
 143: (v12 bro det v0)
 144: (v0 ok ok v0)
 145: (v0 ok det v0)
 146: (v0 bro ok v0)
 147: (v0 bro det v0)
 148: } 1;

--- SET VALUATION R_I3 ---
 231: SET VALUATION R_I3 {(v12 on) (v0 off)} 1;
 232: SET VALUATION R_I4 {(v12 on) (v0 off)} 1;
 233: SET VALUATION R_I5 {(v12 on) (v0 off)} 1;
 234: SET VALUATION R_I6 {(v12 on) (v0 off)} 1;
 235: SET VALUATION R_I7 {(v12 on) (v0 off)} 1;
 236: SET VALUATION R_I8 {(v12 on) (v0 off)} 1;
 237:
 238: SET VALUATION R_OLa {
 239: (v12 ok ok on)
 240: (v12 ok bro off)

--- SET VALUATION R_M3 ---
 260: SET VALUATION R_M3 {(v12 v12) (v0 v0)} 1;
 261: SET VALUATION R_M4 {(v12 v12) (v0 v0)} 1;
 262: SET VALUATION R_M5 {(v12 v12) (v0 v0)} 1;
 263: SET VALUATION R_M6 {(v12 v12) (v0 v0)} 1;
 264: SET VALUATION R_M7 {(v12 v12) (v0 v0)} 1;
 265: SET VALUATION R_M8 {(v12 v12) (v0 v0)} 1;
 266:
 267: SET VALUATION R_MPS {(no high) (yes low)} 1;


## 4. Experiment level L0: complete-information validation

L0 loads the complete BFM model and runs the selected thesis scenarios. It does not remove information. Its purpose is to validate that the BFM implementation behaves consistently with the complete Bayesian-network reference model.

The script loops over the selected scenarios and over the fault-variable map. Each fault is solved by BFM and the result is exported to CSV.

In [5]:

# Key L0 lines showing scenario loop and solving.
def print_excerpt(path, start, end):
    lines = path.read_text(errors='ignore').splitlines()
    for i in range(start, min(end, len(lines))+1):
        print(f"{i:4d}: {lines[i-1]}")

l0_script = paths['matlab_scripts'] / 'export_bfm_L0_results.m'
print_excerpt(l0_script, 78, 125)

  78: scenario_ids = [7, 8, 11, 14];
  79:
  80: % Storage
  81: rows = {};
  82:
  83: % ------------------------------------------------------------
  84: % Run scenarios
  85: % ------------------------------------------------------------
  86:
  87: for s_idx = 1:length(scenario_ids)
  88:
  89:     scenario_id = scenario_ids(s_idx);
  90:
  91:     fprintf('\n============================================================\n');
  92:     fprintf('Scenario %d\n', scenario_id);
  93:     fprintf('============================================================\n');
  94:
  95:     obs = make_scenario_observations(scenario_id);
  96:
  97:     disp('Evidence used:');
  98:     showbel(obs);
  99:
 100:     beliefs_with_evidence = [embelall obs];
 101:
 102:     scenario_rows = {};
 103:
 104:     for k = 1:size(fault_map, 1)
 105:
 106:         bfm_var = fault_map{k, 1};
 107:         bfm_fault_state = fault_map{k, 2};
 108:         bn_fault_var = fault_map{k, 3};
 109:         bn_fault_state = fault_map{k, 4};
 110:
 111:         fprintf('Solving %s...\n', bfm_var);
 112:
 113:         result = solve(beliefs_with_evidence, bfm_var);
 114:
 115:         metrics = extract_binary_fault_metrics(result, bfm_fault_state);
 116:
 117:         scenario_rows(end+1, :) = {
 118:             scenario_id, ...
 119:             'L0_complete', ...
 120:             bn_fault_var, ...
 121:             bn_fault_state, ...
 122:             bfm_var, ...
 123:             bfm_fault_state, ...
 124:             metrics.belief, ...
 125:             metrics.plausibility, ...


## 5. Experiment level L1: local prior ignorance

L1 replaces only the locally relevant prior(s) with full-frame ignorance. This is done by editing the UIL text before conversion to BFM. This means the results are not typed manually; the script changes the model definition and then runs BFM inference.

Examples:

- Scenario 8: the local priors for `SW3` and `C3` are replaced by ignorance.
- Scenario 11: the local priors for `SW6` and `C6` are replaced by ignorance.
- Scenario 7 / 14: battery and/or power subsystem priors are replaced by ignorance.

In [6]:

l1_script = paths['matlab_scripts'] / 'export_bfm_L1_local_prior_ignorance.m'
print_excerpt(l1_script, 104, 135)
print('\nHelper functions that replace priors with ignorance:')
print_excerpt(l1_script, 252, 290)

 104:     txt = fileread(l0_uil);
 105:
 106:     switch scenario_id
 107:
 108:         case 7
 109:             % Battery prior/conditional battery knowledge unknown.
 110:             % PSF prior remains known because M_PSU_short evidence is available.
 111:             txt = replace_battery_conditional_with_ignorance(txt);
 112:
 113:         case 8
 114:             % Local module 3 ambiguity: switch 3 and cable 3 priors unknown.
 115:             txt = replace_switch_prior_with_ignorance(txt, 3);
 116:             txt = replace_cable_prior_with_ignorance(txt, 3);
 117:
 118:         case 11
 119:             % Sparse-evidence module-6 case:
 120:             % switch 6 and cable 6 priors unknown.
 121:             txt = replace_switch_prior_with_ignorance(txt, 6);
 122:             txt = replace_cable_prior_with_ignorance(txt, 6);
 123:
 124:         case 14
 125:             % PSU short + discharged battery:
 126:             % PSF prior and battery conditional knowledge unknown.
 127:             txt = replace_psf_prior_with_ignorance(txt);
 128:             txt = replace_battery_conditional_with_ignorance(txt);
 129:
 130:         otherwise
 131:             error(['Unknown scenario_id: ', num2str(scenario_id)]);
 132:     end
 133:
 134:     fid = fopen(temp_uil, 'w');
 135:     if fid == -1

Helper functions that replace priors with ignorance:
 252: % Local helper functions: prior replacement
 253: % ============================================================
 254:
 255: function txt = replace_psf_prior_with_ignorance(txt)
 256:
 257:     txt = strrep(txt, ...
 258:         'SET VALUATION PR_PSF {yes} 0.005, {no} 0.995;', ...
 259:         'SET VALUATION PR_PSF {no yes} 1;');
 260: end
 261:
 262:
 263: function txt = replace_battery_conditional_with_ignorance(txt)
 264:
 265:     txt = strrep(txt, ...
 266:         'SET CONDITIONAL VALUATION PB0 GIVEN {no}, {exh} 0.080, {good} 0.920;', ...
 267:         'SET CONDITIONAL VALUATION PB0 GIVEN {no}, {good exh} 1;');
 268:
 269:     txt = strrep(txt, ...
 270:         'SET CONDITIONAL VALUATION PB1 GIVEN {yes}, {exh} 0.950, {good} 0.050;', ...
 271:         'SET CONDITIONAL VALUATION PB1 GIVEN {yes}, {good exh} 1;');
 272: end
 273:
 274:
 275: function txt = replace_switch_prior_with_ignorance(txt, idx)
 276:
 277:     old_line = sprintf('SET VALUATION PR_SW%d {det} 0.030, {ok} 0.970;', idx);
 278:     new_line = sprintf('SET VALUATION PR_SW%d {ok det} 1;', idx);
 279:
 280:     txt = strrep(txt, old_line, new_line);
 281: end
 282:
 283:
 284: function txt = replace_cable_prior_with_ignorance(txt, idx)
 285:
 286:     old_line = sprintf('SET VALUATION PR_C%d {bro} 0.020, {ok} 0.980;', idx);
 287:     new_line = sprintf('SET VALUATION PR_C%d {ok bro} 1;', idx);
 288:
 289:     txt = strrep(txt, old_line, new_line);
 290: end


## 6. Experiment level L2: fault-family prior ignorance

L2 removes broader prior families, such as all switch and cable priors in control-chain scenarios. This tests whether the model can still localise a diagnosis when a whole reliability family is unavailable.

Again, the script modifies the UIL model by replacing prior valuations with vacuous mass functions, then converts and solves the model.

In [7]:

l2_script = paths['matlab_scripts'] / 'export_bfm_L2_fault_family_prior_ignorance.m'
print_excerpt(l2_script, 112, 145)
print('\nFamily-level replacement helpers:')
print_excerpt(l2_script, 293, 360)

 112:         case 7
 113:             % Upstream power-family prior ignorance:
 114:             % PSF prior and battery conditional prior unknown.
 115:             %
 116:             % Real-life interpretation:
 117:             % The company may know the circuit and measurements, but not
 118:             % trust reliability estimates for the power subsystem.
 119:             txt = replace_power_subsystem_priors_with_ignorance(txt);
 120:
 121:         case 8
 122:             % Control-chain fault-family prior ignorance:
 123:             % all switch and cable priors unknown.
 124:             %
 125:             % Real-life interpretation:
 126:             % The system can still be observed, but historical reliability
 127:             % data for switch/cable faults is unavailable or unreliable.
 128:             txt = replace_all_switch_priors_with_ignorance(txt);
 129:             txt = replace_all_cable_priors_with_ignorance(txt);
 130:
 131:         case 11
 132:             % Control-chain fault-family prior ignorance under sparse evidence:
 133:             % all switch and cable priors unknown.
 134:             %
 135:             % This is intentionally a hard test: sparse evidence plus
 136:             % no trusted prior database for the control chain.
 137:             txt = replace_all_switch_priors_with_ignorance(txt);
 138:             txt = replace_all_cable_priors_with_ignorance(txt);
 139:
 140:         case 14
 141:             % Upstream power-family prior ignorance:
 142:             % PSF prior and battery conditional prior unknown.
 143:             txt = replace_power_subsystem_priors_with_ignorance(txt);
 144:
 145:         otherwise

Family-level replacement helpers:
 293: % Local helper functions: prior replacement
 294: % ============================================================
 295:
 296: function txt = replace_power_subsystem_priors_with_ignorance(txt)
 297:
 298:     txt = replace_psf_prior_with_ignorance(txt);
 299:     txt = replace_battery_conditional_with_ignorance(txt);
 300: end
 301:
 302:
 303: function txt = replace_psf_prior_with_ignorance(txt)
 304:
 305:     txt = strrep(txt, ...
 306:         'SET VALUATION PR_PSF {yes} 0.005, {no} 0.995;', ...
 307:         'SET VALUATION PR_PSF {no yes} 1;');
 308: end
 309:
 310:
 311: function txt = replace_battery_conditional_with_ignorance(txt)
 312:
 313:     txt = strrep(txt, ...
 314:         'SET CONDITIONAL VALUATION PB0 GIVEN {no}, {exh} 0.080, {good} 0.920;', ...
 315:         'SET CONDITIONAL VALUATION PB0 GIVEN {no}, {good exh} 1;');
 316:
 317:     txt = strrep(txt, ...
 318:         'SET CONDITIONAL VALUATION PB1 GIVEN {yes}, {exh} 0.950, {good} 0.050;', ...
 319:         'SET CONDITIONAL VALUATION PB1 GIVEN {yes}, {good exh} 1;');
 320: end
 321:
 322:
 323: function txt = replace_all_switch_priors_with_ignorance(txt)
 324:
 325:     for idx = 1:8
 326:         txt = replace_switch_prior_with_ignorance(txt, idx);
 327:     end
 328: end
 329:
 330:
 331: function txt = replace_all_cable_priors_with_ignorance(txt)
 332:
 333:     for idx = 1:8
 334:         txt = replace_cable_prior_with_ignorance(txt, idx);
 335:     end
 336:
 337:     % Cable-to-load prior belongs to the cable family.
 338:     txt = strrep(txt, ...
 339:         'SET VALUATION PR_CL {bro} 0.020, {ok} 0.980;', ...
 340:         'SET VALUATION PR_CL {ok bro} 1;');
 341: end
 342:
 343:
 344: function txt = replace_switch_prior_with_ignorance(txt, idx)
 345:
 346:     old_line = sprintf('SET VALUATION PR_SW%d {det} 0.030, {ok} 0.970;', idx);
 347:     new_line = sprintf('SET VALUATION PR_SW%d {ok det} 1;', idx);
 348:
 349:     txt = strrep(txt, old_line, new_line);
 350: end
 351:
 352:
 353: function txt = replace_cable_prior_with_ignorance(txt, idx)
 354:
 355:     old_line = sprintf('SET VALUATION PR_C%d {bro} 0.020, {ok} 0.980;', idx);
 356:     new_line = sprintf('SET VALUATION PR_C%d {ok bro} 1;', idx);
 357:
 358:     txt = strrep(txt, old_line, new_line);
 359: end
 360:


## 7. Intermediate L3 / L3b: observation uncertainty

L3 and L3b are included because they explain how observation uncertainty was represented before the final combined L4 setup.

- L3 discounts the **evidence itself**: 80% mass on the observed value and 20% on the full frame.
- L3b weakens the **visual observation rules** in the model while keeping multimeter relations reliable.

These levels are not the main thesis result tables, but they are useful for showing how observation uncertainty was coded.

In [8]:

l3_script = paths['matlab_scripts'] / 'export_bfm_L3_observation_uncertainty.m'
l3b_script = paths['matlab_scripts'] / 'export_bfm_L3b_observation_rule_uncertainty.m'
print('L3 soft evidence helper:')
print_excerpt(l3_script, 222, 306)
print('\nL3b visual-rule weakening excerpt:')
print_excerpt(l3b_script, 60, 88)

L3 soft evidence helper:
 222: % Local helper function: scenario evidence with observation uncertainty
 223: % ============================================================
 224:
 225: function obs = make_scenario_observations_L3(scenario_id, discount_rate)
 226:
 227:     obs = [];
 228:
 229:     switch scenario_id
 230:
 231:         case 7
 232:             % Scenario 7: battery exhausted.
 233:             % Available evidence is discounted to represent uncertain
 234:             % LED/lamp/multimeter observations.
 235:             obs(end+1) = soft_observe('OPSU', 'off', discount_rate);
 236:
 237:             for n = 1:8
 238:                 obs(end+1) = soft_observe(sprintf('I%d', n), 'off', discount_rate);
 239:             end
 240:
 241:             obs(end+1) = soft_observe('OLa', 'off', discount_rate);
 242:             obs(end+1) = soft_observe('OLi', 'off', discount_rate);
 243:             obs(end+1) = soft_observe('MB', 'v0', discount_rate);
 244:             obs(end+1) = soft_observe('MPS', 'high', discount_rate);
 245:
 246:         case 8
 247:             % Scenario 8: module-3 transition fault.
 248:             % The control-chain observation pattern is discounted:
 249:             % indicators 1-2 on, indicators 3-8 off, lamp off.
 250:             obs(end+1) = soft_observe('OPSU', 'on', discount_rate);
 251:
 252:             obs(end+1) = soft_observe('I1', 'on', discount_rate);
 253:             obs(end+1) = soft_observe('I2', 'on', discount_rate);
 254:
 255:             for n = 3:8
 256:                 obs(end+1) = soft_observe(sprintf('I%d', n), 'off', discount_rate);
 257:             end
 258:
 259:             obs(end+1) = soft_observe('OLa', 'off', discount_rate);
 260:             obs(end+1) = soft_observe('OLi', 'off', discount_rate);
 261:             obs(end+1) = soft_observe('MB', 'v12', discount_rate);
 262:             obs(end+1) = soft_observe('MPS', 'high', discount_rate);
 263:
 264:         case 11
 265:             % Scenario 11: sparse evidence / no detailed tools.
 266:             % This is the hardest observation-uncertainty case because
 267:             % only three observations are available, and all are discounted.
 268:             obs(end+1) = soft_observe('OPSU', 'on', discount_rate);
 269:             obs(end+1) = soft_observe('OLa', 'off', discount_rate);
 270:             obs(end+1) = soft_observe('OLi', 'off', discount_rate);
 271:
 272:         case 14
 273:             % Scenario 14: PSU short + battery discharged.
 274:             % Direct upstream measurements are discounted rather than hard.
 275:             obs(end+1) = soft_observe('OPSU', 'off', discount_rate);
 276:
 277:             for n = 1:8
 278:                 obs(end+1) = soft_observe(sprintf('I%d', n), 'off', discount_rate);
 279:             end
 280:
 281:             obs(end+1) = soft_observe('OLa', 'off', discount_rate);
 282:             obs(end+1) = soft_observe('OLi', 'off', discount_rate);
 283:             obs(end+1) = soft_observe('MB', 'v0', discount_rate);
 284:             obs(end+1) = soft_observe('MPS', 'low', discount_rate);
 285:
 286:         otherwise
 287:             error(['Unknown scenario_id: ', num2str(scenario_id)]);
 288:     end
 289: end
 290:
 291:
 292: function belid = soft_observe(var_name, observed_value, discount_rate)
 293:
 294:     % Create a hard observation, then discount it.
 295:     % If discount_rate = 0.20:
 296:     %   80% remains committed to observed_value
 297:     %   20% is moved to the full frame / ignorance
 298:
 299:     hard_belid = observe(var_name, observed_value);
 300:
 301:     if discount_rate > 0
 302:         soft_belid = discount(hard_belid, discount_rate);
 303:         belid = soft_belid(1);
 304:     else
 305:         belid = hard_belid;
 306:     end

L3b visual-rule weakening excerpt:
  60: % Observation-rule reliability
  61: rule_reliability = 0.80;
  62: rule_ignorance = 1 - rule_reliability;
  63:
  64: % ------------------------------------------------------------
  65: % Build L3b UIL
  66: % ------------------------------------------------------------
  67:
  68: txt = fileread(l0_uil);
  69:
  70: % Weaken OPSU visual rule: Batt -> OPSU
  71: txt = strrep(txt, ...
  72:     'SET VALUATION R_OPSU {(good on) (exh off)} 1;', ...
  73:     sprintf(['SET VALUATION R_OPSU {(good on) (exh off)} %.2f, ' ...
  74:              '{(good on) (good off) (exh on) (exh off)} %.2f;'], ...
  75:     rule_reliability, rule_ignorance));
  76:
  77: % Weaken indicator rules: Vn -> In
  78: for n = 1:8
  79:     old_line = sprintf('SET VALUATION R_I%d {(v12 on) (v0 off)} 1;', n);
  80:
  81:     new_line = sprintf(['SET VALUATION R_I%d {(v12 on) (v0 off)} %.2f, ' ...
  82:                         '{(v12 on) (v12 off) (v0 on) (v0 off)} %.2f;'], ...
  83:         n, rule_reliability, rule_ignorance);
  84:
  85:     txt = strrep(txt, old_line, new_line);
  86: end
  87:
  88: % Weaken lamp rule: V8, CL, LF -> OLa


## 8. Experiment level L4: combined incompleteness

L4 combines several realistic forms of incompleteness:

1. A key observation is missing.
2. Relevant subsystem/fault-family priors are replaced by ignorance.
3. Visual observation rules are weakened.

This is the strongest stress test in the thesis. It uses derived scenarios 15 and 16.

In [9]:

l4_script = paths['matlab_scripts'] / 'export_bfm_L4_combined_incompleteness.m'
print_excerpt(l4_script, 4, 56)
print('\nScenario-level model changes:')
print_excerpt(l4_script, 126, 160)
print('\nVisual rule weakening function:')
print_excerpt(l4_script, 446, 470)

   4: % Export BFM L4 results: combined incompleteness
   5: %
   6: % L4 definition:
   7: %   Combined realistic diagnostic incompleteness:
   8: %     1. A key discriminating observation is missing.
   9: %     2. The relevant subsystem/fault-family priors are unknown.
  10: %     3. Visual observation rules are weakened.
  11: %
  12: % Derived scenarios:
  13: %
  14: %   Scenario 15:
  15: %     Battery discharge observed, PSU-short measurement unavailable.
  16: %     Tests ambiguity between:
  17: %       - battery-only exhaustion
  18: %       - hidden PSU-short-induced battery discharge
  19: %
  20: %     Evidence:
  21: %       OPSU = off
  22: %       I1-I8 = off
  23: %       OLa = off
  24: %       OLi = off
  25: %       MB = v0
  26: %       MPS = missing
  27: %
  28: %     Missing/uncertain knowledge:
  29: %       - PSF prior unknown
  30: %       - battery conditional prior unknown
  31: %       - visual symptom rules weakened
  32: %
  33: %   Scenario 16:
  34: %     Module-3 transition fault, but boundary indicator I3 unavailable.
  35: %     Tests whether localization remains physically constrained when the
  36: %     key boundary observation is missing.
  37: %
  38: %     Evidence:
  39: %       OPSU = on
  40: %       I1 = on
  41: %       I2 = on
  42: %       I3 = missing
  43: %       I4-I8 = off
  44: %       OLa = off
  45: %       OLi = off
  46: %       MB = v12
  47: %       MPS = high
  48: %
  49: %     Missing/uncertain knowledge:
  50: %       - all switch/cable priors unknown
  51: %       - visual symptom rules weakened
  52: %
  53: % Output:
  54: %   runs/bfm_L4_combined_incompleteness_results.csv
  55: % ============================================================
  56:

Scenario-level model changes:
 126: for s_idx = 1:length(scenario_ids)
 127:
 128:     scenario_id = scenario_ids(s_idx);
 129:
 130:     fprintf('\n============================================================\n');
 131:     fprintf('Scenario %d - L4 combined incompleteness\n', scenario_id);
 132:     fprintf('============================================================\n');
 133:
 134:     % --------------------------------------------------------
 135:     % Build scenario-specific L4 UIL
 136:     % --------------------------------------------------------
 137:
 138:     txt = fileread(l0_uil);
 139:
 140:     % Weaken visual observation rules for all L4 scenarios.
 141:     txt = weaken_visual_observation_rules(txt, rule_reliability, rule_ignorance);
 142:
 143:     switch scenario_id
 144:
 145:         case 15
 146:             % Battery/PSU ambiguity:
 147:             % key MPS measurement is missing, and power-subsystem priors
 148:             % are unknown.
 149:             txt = replace_power_subsystem_priors_with_ignorance(txt);
 150:
 151:         case 16
 152:             % Module-3 boundary ambiguity:
 153:             % key I3 observation is missing, and switch/cable family
 154:             % priors are unknown.
 155:             txt = replace_all_switch_priors_with_ignorance(txt);
 156:             txt = replace_all_cable_priors_with_ignorance(txt);
 157:
 158:         otherwise
 159:             error(['Unknown L4 scenario_id: ', num2str(scenario_id)]);
 160:     end

Visual rule weakening function:
 446: % Helper functions: weaken visual observation rules
 447: % ============================================================
 448:
 449: function txt = weaken_visual_observation_rules(txt, rule_reliability, rule_ignorance)
 450:
 451:     % Weaken OPSU visual rule: Batt -> OPSU
 452:     txt = strrep(txt, ...
 453:         'SET VALUATION R_OPSU {(good on) (exh off)} 1;', ...
 454:         sprintf(['SET VALUATION R_OPSU {(good on) (exh off)} %.2f, ' ...
 455:                  '{(good on) (good off) (exh on) (exh off)} %.2f;'], ...
 456:         rule_reliability, rule_ignorance));
 457:
 458:     % Weaken indicator rules: Vn -> In
 459:     for n = 1:8
 460:         old_line = sprintf('SET VALUATION R_I%d {(v12 on) (v0 off)} 1;', n);
 461:
 462:         new_line = sprintf(['SET VALUATION R_I%d {(v12 on) (v0 off)} %.2f, ' ...
 463:                             '{(v12 on) (v12 off) (v0 on) (v0 off)} %.2f;'], ...
 464:             n, rule_reliability, rule_ignorance);
 465:
 466:         txt = strrep(txt, old_line, new_line);
 467:     end
 468:
 469:     % Weaken lamp rule: V8, CL, LF -> OLa
 470:     old_OLa = [


## 9. Evidence creation and fault mapping

The scripts use a fault map to connect the short BFM names to the original BN-style fault names. Evidence is created per scenario using helper functions such as `make_scenario_observations` or `make_scenario_observations_L4`.

This is expected and acceptable: the scenarios are the experimental inputs. What is not hardcoded are the final belief/plausibility results, which are generated by BFM inference.

In [10]:

print('L4 evidence helper for derived scenarios:')
print_excerpt(l4_script, 310, 375)

L4 evidence helper for derived scenarios:
 310: % Helper functions: scenario evidence
 311: % ============================================================
 312:
 313: function obs = make_scenario_observations_L4(scenario_id)
 314:
 315:     obs = [];
 316:
 317:     switch scenario_id
 318:
 319:         case 15
 320:             % Battery discharge observed, PSU-short measurement missing.
 321:             %
 322:             % Evidence:
 323:             %   OPSU = off
 324:             %   I1-I8 = off
 325:             %   OLa = off
 326:             %   OLi = off
 327:             %   MB = v0
 328:             %   MPS = missing
 329:
 330:             obs(end+1) = observe('OPSU', 'off');
 331:
 332:             for n = 1:8
 333:                 obs(end+1) = observe(sprintf('I%d', n), 'off');
 334:             end
 335:
 336:             obs(end+1) = observe('OLa', 'off');
 337:             obs(end+1) = observe('OLi', 'off');
 338:             obs(end+1) = observe('MB', 'v0');
 339:
 340:             % MPS intentionally not observed.
 341:
 342:         case 16
 343:             % Module-3 transition pattern with I3 missing.
 344:             %
 345:             % Evidence:
 346:             %   OPSU = on
 347:             %   I1 = on
 348:             %   I2 = on
 349:             %   I3 = missing
 350:             %   I4-I8 = off
 351:             %   OLa = off
 352:             %   OLi = off
 353:             %   MB = v12
 354:             %   MPS = high
 355:
 356:             obs(end+1) = observe('OPSU', 'on');
 357:             obs(end+1) = observe('I1', 'on');
 358:             obs(end+1) = observe('I2', 'on');
 359:
 360:             % I3 intentionally not observed.
 361:
 362:             for n = 4:8
 363:                 obs(end+1) = observe(sprintf('I%d', n), 'off');
 364:             end
 365:
 366:             obs(end+1) = observe('OLa', 'off');
 367:             obs(end+1) = observe('OLi', 'off');
 368:             obs(end+1) = observe('MB', 'v12');
 369:             obs(end+1) = observe('MPS', 'high');
 370:
 371:         otherwise
 372:             error(['Unknown L4 scenario_id: ', num2str(scenario_id)]);
 373:     end
 374: end
 375:


## 10. Extracting belief, plausibility, width, and conflict

The BFM `showbel` output is a text/table representation of a belief function. The MATLAB scripts parse this output to extract:

- belief in the queried fault state;
- plausibility of the queried fault state;
- width = plausibility − belief;
- empty-set mass, used as a conflict indicator.

This extraction is mechanical and is applied uniformly to all faults and scenarios.

In [11]:

print('Belief/plausibility extraction helper from L4 script:')
print_excerpt(l4_script, 539, 650)

Belief/plausibility extraction helper from L4 script:
 539: % Helper function: extract belief/plausibility
 540: % ============================================================
 541:
 542: function metrics = extract_binary_fault_metrics(result_belief_id, fault_state)
 543:
 544:     tbl = showbel(result_belief_id);
 545:     lines = cellstr(tbl);
 546:
 547:     belief = 0;
 548:     plausibility = 0;
 549:     empty_mass = 0;
 550:
 551:     current_states = {};
 552:     current_raw_mass = NaN;
 553:     current_norm_mass = NaN;
 554:
 555:     for i = 1:length(lines)
 556:
 557:         line = strtrim(lines{i});
 558:
 559:         if isempty(line)
 560:             continue;
 561:         end
 562:
 563:         if contains(line, 'value')
 564:             continue;
 565:         end
 566:
 567:         if contains(line, '---')
 568:
 569:             if ~isempty(current_states) || ~isnan(current_raw_mass) || ~isnan(current_norm_mass)
 570:
 571:                 [belief, plausibility, empty_mass] = process_focal_set( ...
 572:                     current_states, current_raw_mass, current_norm_mass, ...
 573:                     fault_state, belief, plausibility, empty_mass);
 574:
 575:                 current_states = {};
 576:                 current_raw_mass = NaN;
 577:                 current_norm_mass = NaN;
 578:             end
 579:
 580:             continue;
 581:         end
 582:
 583:         if ~contains(line, '|')
 584:             continue;
 585:         end
 586:
 587:         parts = split(line, '|');
 588:
 589:         if length(parts) < 2
 590:             continue;
 591:         end
 592:
 593:         state = strtrim(parts{1});
 594:         raw_value_str = strtrim(parts{2});
 595:
 596:         norm_value_str = '';
 597:         if length(parts) >= 3
 598:             norm_value_str = strtrim(parts{3});
 599:         end
 600:
 601:         raw_value = str2double(raw_value_str);
 602:         norm_value = str2double(norm_value_str);
 603:
 604:         if strcmp(state, '')
 605:             if ~isnan(raw_value)
 606:                 current_states = {};
 607:                 current_raw_mass = raw_value;
 608:                 current_norm_mass = NaN;
 609:             end
 610:             continue;
 611:         end
 612:
 613:         current_states{end+1} = state;
 614:
 615:         if ~isnan(raw_value)
 616:             current_raw_mass = raw_value;
 617:         end
 618:
 619:         if ~isnan(norm_value)
 620:             current_norm_mass = norm_value;
 621:         end
 622:     end
 623:
 624:     if ~isempty(current_states) || ~isnan(current_raw_mass) || ~isnan(current_norm_mass)
 625:         [belief, plausibility, empty_mass] = process_focal_set( ...
 626:             current_states, current_raw_mass, current_norm_mass, ...
 627:             fault_state, belief, plausibility, empty_mass);
 628:     end
 629:
 630:     metrics.belief = belief;
 631:     metrics.plausibility = plausibility;
 632:     metrics.width = plausibility - belief;
 633:     metrics.empty_mass = empty_mass;
 634:
 635: end
 636:
 637:
 638: function [belief, plausibility, empty_mass] = process_focal_set( ...
 639:     current_states, current_raw_mass, current_norm_mass, fault_state, ...
 640:     belief, plausibility, empty_mass)
 641:
 642:     if ~isnan(current_norm_mass)
 643:         mass = current_norm_mass;
 644:     elseif ~isnan(current_raw_mass)
 645:         mass = current_raw_mass;
 646:     else
 647:         mass = NaN;
 648:     end
 649:
 650:     if isnan(mass)


## 11. Checking the exported CSV results

The CSV files are the actual result source for the thesis tables. The next cells load the raw CSVs, check their columns, and create compact summaries.

In [12]:

result_files = sorted(paths['results'].glob('bfm_*.csv'))
frames = []
for f in result_files:
    df = pd.read_csv(f)
    if 'width' not in df.columns:
        df['width'] = df['plausibility'] - df['belief']
    frames.append(df)
    print(f.name, df.shape, list(df.columns))

all_results = pd.concat(frames, ignore_index=True)
all_results.head()

bfm_L0_results.csv (80, 11) ['scenario_id', 'level', 'bn_fault_var', 'bn_fault_state', 'bfm_var', 'bfm_fault_state', 'belief', 'plausibility', 'width', 'empty_set_mass', 'bfm_rank']
bfm_L1_local_prior_ignorance_results_ranked.csv (80, 12) ['scenario_id', 'level', 'bn_fault_var', 'bn_fault_state', 'bfm_var', 'bfm_fault_state', 'belief', 'plausibility', 'width', 'empty_set_mass', 'rank_by_belief', 'rank_by_plausibility']
bfm_L2_fault_family_prior_ignorance_results.csv (80, 12) ['scenario_id', 'level', 'bn_fault_var', 'bn_fault_state', 'bfm_var', 'bfm_fault_state', 'belief', 'plausibility', 'width', 'empty_set_mass', 'rank_by_belief', 'rank_by_plausibility']
bfm_L4_combined_incompleteness_results.csv (40, 12) ['scenario_id', 'level', 'bn_fault_var', 'bn_fault_state', 'bfm_var', 'bfm_fault_state', 'belief', 'plausibility', 'width', 'empty_set_mass', 'rank_by_belief', 'rank_by_plausibility']

   scenario_id        level  ... rank_by_belief rank_by_plausibility
0            7  L0_complete  ...            NaN                  NaN
1            7  L0_complete  ...            NaN                  NaN
2            7  L0_complete  ...            NaN                  NaN
3            7  L0_complete  ...            NaN                  NaN
4            7  L0_complete  ...            NaN                  NaN

[5 rows x 13 columns]

In [13]:

# Top candidates by scenario and level.
summary_frames = []
for f, df in zip(result_files, frames):
    rank_col = 'rank_by_belief' if 'rank_by_belief' in df.columns else 'bfm_rank'
    top = df.sort_values(['scenario_id', rank_col]).groupby('scenario_id').head(5).copy()
    top['source_file'] = f.name
    summary_frames.append(top)

pd.concat(summary_frames)[['source_file','scenario_id','level','bfm_var','bfm_fault_state','belief','plausibility','width','empty_set_mass']]

                                   source_file  ...  empty_set_mass
0                           bfm_L0_results.csv  ...          0.9204
1                           bfm_L0_results.csv  ...          0.9204
2                           bfm_L0_results.csv  ...          0.9204
3                           bfm_L0_results.csv  ...          0.9204
4                           bfm_L0_results.csv  ...          0.9204
..                                         ...  ...             ...
20  bfm_L4_combined_incompleteness_results.csv  ...          0.0846
21  bfm_L4_combined_incompleteness_results.csv  ...          0.0846
22  bfm_L4_combined_incompleteness_results.csv  ...          0.0846
23  bfm_L4_combined_incompleteness_results.csv  ...          0.0846
24  bfm_L4_combined_incompleteness_results.csv  ...          0.0846

[70 rows x 9 columns]


## 12. Scenario 8 as the clearest example

Scenario 8 is the clearest demonstration of the thesis argument. Under complete information, L0 ranks `SW3` and `C3` using precise values. When priors are removed, the model no longer has a justified basis for committing to one exact component, so belief can fall while plausibility remains high.

In [14]:

scenario8 = all_results[(all_results['scenario_id'] == 8) & (all_results['bfm_var'].isin(['SW3','C3']))]
scenario8[['level','bfm_var','bfm_fault_state','belief','plausibility','width','empty_set_mass']].sort_values(['level','bfm_var'])

                               level bfm_var  ... width  empty_set_mass
21                       L0_complete      C3  ...   0.0         0.95914
20                       L0_complete     SW3  ...   0.0         0.95914
119         L1_local_prior_ignorance      C3  ...   1.0         0.17281
116         L1_local_prior_ignorance     SW3  ...   1.0         0.17281
187  L2_fault_family_prior_ignorance      C3  ...   1.0         0.08460
181  L2_fault_family_prior_ignorance     SW3  ...   1.0         0.08460

[6 rows x 7 columns]


## 13. Conflict / empty-set mass

The empty-set mass is reported separately as conflict between the combined evidence and model assumptions. It is not the same as belief in a fault. In this thesis, high L0 conflict largely reflects tension between rare-fault priors and strong evidence that a fault occurred.

In [15]:

conflict = (
    all_results.groupby(['scenario_id','level'], as_index=False)['empty_set_mass']
    .first()
    .pivot(index='scenario_id', columns='level', values='empty_set_mass')
)
conflict

level        L0_complete  ...  L4_combined_incompleteness
scenario_id               ...
7                0.92040  ...                         NaN
8                0.95914  ...                         NaN
11               0.68251  ...                         NaN
14               0.99525  ...                         NaN
15                   NaN  ...                      0.0000
16                   NaN  ...                      0.0846

[6 rows x 4 columns]


## 14. What this notebook shows

This notebook shows that:

1. The model is defined in readable UIL files.
2. MATLAB scripts modify UIL files to create incompleteness levels.
3. BFM functions (`uil2bm`, `condiembed`, `keepbel`, `solve`, `showbel`) are used for inference.
4. Results are exported to CSV.
5. Thesis tables can be regenerated from CSV outputs.

The implementation therefore does not consist of manually hardcoded thesis result values. The hardcoded parts are the experimental design inputs: scenarios, evidence, mappings, and the intended incompleteness manipulations.