# Results analysis

This notebook loads the raw BFM CSV outputs and reproduces the compact summaries used in the thesis.

In [1]:

from pathlib import Path
import pandas as pd
ROOT = Path('..').resolve()
RAW = ROOT / 'results' / 'raw'
files = [
    'bfm_L0_results.csv',
    'bfm_L1_local_prior_ignorance_results_ranked.csv',
    'bfm_L2_fault_family_prior_ignorance_results.csv',
    'bfm_L4_combined_incompleteness_results.csv',
]
frames = []
for file in files:
    df = pd.read_csv(RAW / file)
    if 'width' not in df.columns:
        df['width'] = df['plausibility'] - df['belief']
    df['source_file'] = file
    frames.append(df)
all_results = pd.concat(frames, ignore_index=True)
all_results.head()

   scenario_id        level  ... rank_by_belief rank_by_plausibility
0            7  L0_complete  ...            NaN                  NaN
1            7  L0_complete  ...            NaN                  NaN
2            7  L0_complete  ...            NaN                  NaN
3            7  L0_complete  ...            NaN                  NaN
4            7  L0_complete  ...            NaN                  NaN

[5 rows x 14 columns]

In [2]:

# Conflict table
conflict = all_results.groupby(['scenario_id','level'], as_index=False)['empty_set_mass'].first()
conflict_pivot = conflict.pivot(index='scenario_id', columns='level', values='empty_set_mass')
conflict_pivot

level        L0_complete  ...  L4_combined_incompleteness
scenario_id               ...
7                0.92040  ...                         NaN
8                0.95914  ...                         NaN
11               0.68251  ...                         NaN
14               0.99525  ...                         NaN
15                   NaN  ...                      0.0000
16                   NaN  ...                      0.0846

[6 rows x 4 columns]

In [3]:

# Scenario 8 progression
all_results[(all_results.scenario_id == 8) & (all_results.bfm_var.isin(['SW3','C3']))][
    ['level','bfm_var','belief','plausibility','width','empty_set_mass']
].sort_values(['level','bfm_var'])

                               level bfm_var  ...  width  empty_set_mass
21                       L0_complete      C3  ...    0.0         0.95914
20                       L0_complete     SW3  ...    0.0         0.95914
119         L1_local_prior_ignorance      C3  ...    1.0         0.17281
116         L1_local_prior_ignorance     SW3  ...    1.0         0.17281
187  L2_fault_family_prior_ignorance      C3  ...    1.0         0.08460
181  L2_fault_family_prior_ignorance     SW3  ...    1.0         0.08460

[6 rows x 6 columns]

In [4]:

# Top candidates for each scenario/level by belief
rank_cols = []
for level, g in all_results.groupby('level'):
    rank_col = 'rank_by_belief' if 'rank_by_belief' in g.columns and g['rank_by_belief'].notna().any() else 'bfm_rank'
    top = g.sort_values(['scenario_id', rank_col]).groupby('scenario_id').head(5)
    display(top[['scenario_id','level','bfm_var','bfm_fault_state','belief','plausibility','width','empty_set_mass']])

    scenario_id        level bfm_var  ... plausibility  width  empty_set_mass
0             7  L0_complete    Batt  ...      1.00000    0.0         0.92040
1             7  L0_complete     SW1  ...      0.03000    0.0         0.92040
2             7  L0_complete     SW2  ...      0.03000    0.0         0.92040
3             7  L0_complete     SW3  ...      0.03000    0.0         0.92040
4             7  L0_complete     SW4  ...      0.03000    0.0         0.92040
20            8  L0_complete     SW3  ...      0.60729    0.0         0.95914
21            8  L0_complete      C3  ...      0.40486    0.0         0.95914
22            8  L0_complete     SW4  ...      0.03000    0.0         0.95914
23            8  L0_complete     SW5  ...      0.03000    0.0         0.95914
24            8  L0_complete     SW6  ...      0.03000    0.0         0.95914
40           11  L0_complete     SW1  ...      0.08652    0.0         0.68251
41           11  L0_complete     SW2  ...      0.08652    0.0         0.68251
42           11  L0_complete     SW3  ...      0.08652    0.0         0.68251
43           11  L0_complete     SW4  ...      0.08652    0.0         0.68251
44           11  L0_complete     SW5  ...      0.08652    0.0         0.68251
60           14  L0_complete     PSF  ...      1.00000    0.0         0.99525
61           14  L0_complete    Batt  ...      1.00000    0.0         0.99525
62           14  L0_complete     SW1  ...      0.03000    0.0         0.99525
63           14  L0_complete     SW2  ...      0.03000    0.0         0.99525
64           14  L0_complete     SW3  ...      0.03000    0.0         0.99525

[20 rows x 8 columns]

     scenario_id                     level  ... width empty_set_mass
80             7  L1_local_prior_ignorance  ...   0.0        0.00500
81             7  L1_local_prior_ignorance  ...   0.0        0.00500
82             7  L1_local_prior_ignorance  ...   0.0        0.00500
83             7  L1_local_prior_ignorance  ...   0.0        0.00500
84             7  L1_local_prior_ignorance  ...   0.0        0.00500
100            8  L1_local_prior_ignorance  ...   0.0        0.17281
101            8  L1_local_prior_ignorance  ...   0.0        0.17281
102            8  L1_local_prior_ignorance  ...   0.0        0.17281
103            8  L1_local_prior_ignorance  ...   0.0        0.17281
104            8  L1_local_prior_ignorance  ...   0.0        0.17281
120           11  L1_local_prior_ignorance  ...   0.0        0.08435
121           11  L1_local_prior_ignorance  ...   0.0        0.08435
122           11  L1_local_prior_ignorance  ...   0.0        0.08435
123           11  L1_local_prior_ignorance  ...   0.0        0.08435
124           11  L1_local_prior_ignorance  ...   0.0        0.08435
140           14  L1_local_prior_ignorance  ...   0.0        0.00000
141           14  L1_local_prior_ignorance  ...   0.0        0.00000
142           14  L1_local_prior_ignorance  ...   0.0        0.00000
143           14  L1_local_prior_ignorance  ...   0.0        0.00000
144           14  L1_local_prior_ignorance  ...   0.0        0.00000

[20 rows x 8 columns]

     scenario_id                            level  ... width empty_set_mass
160            7  L2_fault_family_prior_ignorance  ...   0.0        0.00000
161            7  L2_fault_family_prior_ignorance  ...   0.0        0.00000
162            7  L2_fault_family_prior_ignorance  ...   0.0        0.00000
163            7  L2_fault_family_prior_ignorance  ...   0.0        0.00000
164            7  L2_fault_family_prior_ignorance  ...   0.0        0.00000
180            8  L2_fault_family_prior_ignorance  ...   0.0        0.08460
181            8  L2_fault_family_prior_ignorance  ...   1.0        0.08460
182            8  L2_fault_family_prior_ignorance  ...   1.0        0.08460
183            8  L2_fault_family_prior_ignorance  ...   1.0        0.08460
184            8  L2_fault_family_prior_ignorance  ...   1.0        0.08460
200           11  L2_fault_family_prior_ignorance  ...   0.0        0.08435
201           11  L2_fault_family_prior_ignorance  ...   0.0        0.08435
202           11  L2_fault_family_prior_ignorance  ...   1.0        0.08435
203           11  L2_fault_family_prior_ignorance  ...   1.0        0.08435
204           11  L2_fault_family_prior_ignorance  ...   1.0        0.08435
220           14  L2_fault_family_prior_ignorance  ...   0.0        0.00000
221           14  L2_fault_family_prior_ignorance  ...   0.0        0.00000
222           14  L2_fault_family_prior_ignorance  ...   0.0        0.00000
223           14  L2_fault_family_prior_ignorance  ...   0.0        0.00000
224           14  L2_fault_family_prior_ignorance  ...   0.0        0.00000

[20 rows x 8 columns]

     scenario_id                       level  ... width empty_set_mass
240           15  L4_combined_incompleteness  ...   0.0         0.0000
241           15  L4_combined_incompleteness  ...   0.0         0.0000
242           15  L4_combined_incompleteness  ...   0.0         0.0000
243           15  L4_combined_incompleteness  ...   0.0         0.0000
244           15  L4_combined_incompleteness  ...   0.0         0.0000
260           16  L4_combined_incompleteness  ...   0.0         0.0846
261           16  L4_combined_incompleteness  ...   1.0         0.0846
262           16  L4_combined_incompleteness  ...   1.0         0.0846
263           16  L4_combined_incompleteness  ...   1.0         0.0846
264           16  L4_combined_incompleteness  ...   1.0         0.0846

[10 rows x 8 columns]